[project]
name = "bamboost"
dynamic = ["version"]
description = "A light weight database manager using HDF5"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Flavio Lorez", email = "florez@ethz.ch" },
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["hdf5", "database", "database-manager"]
requires-python = ">=3.9"
dependencies = [
    "build>=1.2.2.post1",
    "jinja2>=3.1.5",
    "lazy-loader>=0.4",
    "h5py",
    "numpy",
    "pandas",
    "toolz>=1.0.0",
    "typing-extensions>=4.12.2",
    "sqlalchemy>=2.0.36",
]

[project.urls]
Homepage = "https://bamboost.ch/"
repository = "https://gitlab.com/cmbm-ethz/bamboost"
changelog = "https://gitlab.com/cmbm-ethz/bamboost/-/tree/main/CHANGELOG.md"

[build-system]
requires = [
    "hatchling",
    "versioningit",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit]
default-version = "0.0.dev0"

[dependency-groups]
dev = [
    "mypy[mypyc]>=1.13.0",
    "ipykernel>=6.29.5",
    "ipython>=8.18.1",
    "pip>=24.3.1",
    "twine>=5.1.1",
    "ipywidgets>=8.1.5",
    "textual-dev>=1.7.0",
]
mpi = [
    "mpi4py>=3.1.0",
]
cli = [
    "rich-argparse>=1.6.0",
    "textual>=1.0.0",
    "simple-parsing",
]
test = [
    "pytest",
    "pytest-cov",
]

[tool.pyright]
pythonVersion = "3.9"
pythonPlatform = "Linux"
typeCheckingMode = "basic"
reportOptionalMemberAccess = false
reportOptionalSubscript = false

[tool.bamboost.index]
isolated = true

[tool.bamboost.options]
mpi = true
sortTableKey = "created_at"
