# pyproject.toml

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bamboost"
version = "0.5.1"
description = "A light weight database manager using HDF5"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "Flavio Lorez", email = "florez@ethz.ch" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["hdf5", "database", "database-manager"]
dependencies = [
    "h5py",
    "numpy",
    "pandas",
    "typing_extensions>=4.5",
    'tomli; python_version < "3.11"',
]
requires-python = ">=3.7"

[project.optional-dependencies]
mpi = [
    "mpi4py",
]

[project.urls]
Homepage = "https://bamboost.ch/"
repository = "https://gitlab.com/cmbm-ethz/bamboost"
changelog = "https://gitlab.com/cmbm-ethz/bamboost/-/tree/main/CHANGELOG.md"

[tool.setuptools.packages.find]
include = ["bamboost", "bamboost*"]
