[project]
name = "bamboost"
dynamic = ["version"]
description = "A light weight database manager using HDF5"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Flavio Lorez", email = "florez@ethz.ch" },
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["hdf5", "database", "database-manager"]
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "typing-extensions>=4.12.2",
]

[project.urls]
Homepage = "https://bamboost.ch/"
repository = "https://gitlab.com/cmbm-ethz/bamboost"
changelog = "https://gitlab.com/cmbm-ethz/bamboost/-/tree/main/CHANGELOG.md"

[build-system]
requires = [
    "hatchling",
    "versioningit",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=8.18.1",
    "pip>=24.3.1",
    "twine>=5.1.1",
]

[tool.pyright]
pythonVersion = "3.9"
pythonPlatform = "Linux"
typeCheckingMode = "basic"
