[build-system]
requires = ["setuptools", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "bamboost"
dynamic = ["version"]
description = "A light weight database manager using HDF5"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "Flavio Lorez", email = "florez@ethz.ch" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["hdf5", "database", "database-manager"]
dependencies = [
    "h5py",
    "numpy",
    "pandas",
    "rich",
    "typing_extensions>=4.5",
    'tomli; python_version < "3.11"',
]
requires-python = ">=3.7"

[project.optional-dependencies]
mpi = [
    "mpi4py",
]
test = [
    "pytest",
    "pytest-cov",
]
tui = [
    "urwid",
    "fuzzywuzzy",
    "pyperclip",
    "argcomplete",
    "hfive",
]

[project.entry-points.console_scripts]
bamboostcli = "bamboost.cli:main"
bb-job = "bamboost.cli:job"
bamboost = "bamboost.tui.app:main"
hdfview = "bamboost.tui.pages.hdfview:main"

[project.urls]
Homepage = "https://bamboost.ch/"
repository = "https://gitlab.com/cmbm-ethz/bamboost"
changelog = "https://gitlab.com/cmbm-ethz/bamboost/-/tree/main/CHANGELOG.md"

[tool.setuptools.packages.find]
include = ["bamboost", "bamboost*"]

[tool.setuptools_scm]
version_file = "bamboost/_version.py"

[tool.pyright]
include = [
    "bamboost",
    "tests",
]
exclude = ["**/build"]

typeCheckingMode = "off"
autoImportCompletions = true
