# Config file for bamboost

[options]
# uncomment to disable mpi support
# mpi = False

# default column to sort dataframes by
# sort_table_key = 'time_stamp'

[index]
# the list of paths to search for databases
paths = []
